a=int(input("Enter first number: "))
b=int(input("Enter Second number: "))

#Bitwise Operators(&,|,~,^,>>,<<)
print("a & b", a & b)
print("a | b", a | b)
print(" ~b",  ~b)
print("a ^ b", a ^ b)
print ("a<<", a<<1)
print("b>>", b>>1)